version: '2'

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
    - 8080:8080
    depends_on:
      - db

  db:
    image: 'mysql'
    container_name: mysql-latest
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ems
        MYSQL_USER: root
        MYSQL_PASSWORD: secret

